# Generated by Django 4.2 on 2023-10-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crud_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
